### PR TITLE
Improve energy efficiency by applying Cache Energy Pattern

### PR DESCRIPTION
**Pull request by anasofiagribeiro**
This improves the energy efficiency of Timetable by applying the Cache Energy Pattern for mobile applications.

The energy pattern was applied in NotificationPublisher.java . The general idea is to avoid performing unnecessary operations by using cache mechanisms. In particular, the operations in method onReceive will only execute if the message changes.

### CODE REVIEW

**Comment by smilix** [comment]
I think this commit will break some notification. In this case the notification text is always the same and if the message is not different from the one received before the notification will be swallowed. That should not happen.

**Comment by anasofiagribeiro** [comment]
Thank you for your answer. After further consideration, in the case of notifications, this energy pattern is not be the most suitable since it may break some of them, as you pointed out. With this in mind, I will close the pull request.

**Comment by Catfriend1** [comment]
Hmm interesting, this seems like bot activity or templated pr because I and the newpipe project got this submission as well. Strange. And jff also went into the pr discussion on all of these project pr's. I wonder why we get those postings about the energy submission because I don't know what this should achieve/solve exactly.

**Comment by jff** [comment]
Hi @Catfriend1, thanks for your comment. As part of her MSc, @anasofiagribeiro is developing an Android Studio plugin that suggests the application of [energy patterns for Android mobile apps](https://tqrg.github.io/energy-patterns). This is based on recent research published by colleagues in the _Journal of Empirical Software Engineering_ ([link to paper](https://arxiv.org/pdf/1901.03302.pdf)). Incidentally, this is an active topic in the research community: there have been some recent research papers on this topic at top conferences, such as MobileSoft.

@anasofiagribeiro is evaluating her implementation on open-source F-Droid projects, with the goal to contribute and improve open source projects. She is also hoping to contribute to the [catalog](https://tqrg.github.io/energy-patterns) with more real-world examples. 

With respect to the PRs in multiple projects: we made a selection of F-Droid projects, the plugin was applied to these projects, and it found opportunities to apply some patterns. We reviewed the changes made by the plugin and @anasofiagribeiro  created the PRs. All the PRs were created manually, so there are no bots involved. 

In the case of this PR, we both missed the problem (sorry for this @smilix :( ). However, several PRs created by @anasofiagribeiro have been accepted by maintainers of other projects.

I hope this clarifies what is going on. If you have any further questions, please let us know.

**Comment by Catfriend1** [comment]
Hi @jff , thank you for clarification on the subject of the pr's . I need to take a deeper look at your links provided to understand how the improvement works in detail. Then it's all good in the end :-).

**Pull request closed without merging**
